{% set python_min = '3.11' %}
{% set name = "tabulardelta" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tabulardelta-{{ version }}.tar.gz
  sha256: 78909b821fa43521f76ceb78a1bab901fa8626f0f11b1e086afdec4fb847414f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24.4,<3
    - pandas >=2.0.3,<3

test:
  imports:
    - tabulardelta
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/quantco/tabulardelta
  summary: Simplify table comparisons.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DominikZuercherQC
    - AaronTacke
